apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: payment-r
spec:
  type: git 
  params:
    - name: revision
      value: maha-dev
    - name: url
      value: https://github.com/M404h/level3-project

