apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: shipping-svc
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: deploy, delete
spec:
  description: >-
    This Task deploys (or delete) a Kubernetes resource (pod). It uses
    kubectl for that.
  params:
  - name: action
    description: Action on the resource
  - name: manifest
    description: Content of the resource to deploy
  - name: output
    default: ""
    description: An express to retrieval data from resource.
  - name: image
    default: index.docker.io/aipipeline/kubeclient:v0.0.2  # it is huge
    description: Kubectl wrapper image
  steps:
  - name: kubeconfig
    image: $(params.image)
    args:
      - --action=$(params.action)
      - --manifest=$(params.manifest)
      - --output=$(params.output)
