apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-taskrun
spec:
  serviceAccountName: maha-sa
  taskRef:
    name: shipping-task
  params:
  - name: IMAGE
    value: "ma404/shipping"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: shipping-r

