apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  pipelineRef:
    name: queue-pl
  serviceAccountName: maha-sa 
  resources:
    - name: level3-project
      resourceRef: 
        name: queue-r
