apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-taskrun
spec:
  serviceAccountName: maha-sa
  taskRef:
    name: queue-task
  params:
  - name: IMAGE
    value: "ma404/queue-master"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: queue-r

