apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-taskrun
spec:
  serviceAccountName: maha-sa
  taskRef:
    name: orders-task
  params:
  - name: IMAGE
    value: "ma404/carts"
  resources:
    inputs:
    - name: level3-project
      resourceRef:
        name: carts-r
